# Generated by Django 3.2.5 on 2021-08-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
