# Generated by Django 3.2.6 on 2021-08-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='slug',
        ),
    ]
