# Generated by Django 3.2.5 on 2021-08-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_ejercicio_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='comments',
        ),
    ]
